Desktop/myfirstprojectonjango/Resto-master/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('api/v1/get_all_users/', views.UserListAPIView.as_view(), name='get-all-users-api'),
    path('api/v1/update_user/', views.UserUpdateAPIView.as_view(), name='create-users-api'),

    path('api/v1/get_all_feedbacks/', views.FeedbackListAPIView.as_view(), name='get-all-feedbacks-api'),
    path('api/v1/create_feedback/', views.FeedbackCreateAPIView.as_view(), name='create-feedback-api'),
    path('api/v1/update_feedback/', views.FeedbackUpdateAPIView.as_view(), name='update-feedback-api'),
    path('api/v1/delete_feedback/', views.FeedbackDeleteView.as_view(), name='delete-feedback-api'),

    path('api/v1/get_all_comments/', views.CommentListAPIView.as_view(), name='get-all-comments-api'),
    path('api/v1/create_comment/', views.CommentListAPIView.as_view(), name='update-comment-api'),
    path('api/v1/update_comment/', views.UserDetailsAPIView.as_view(), name='update-comment-api'),
    path('api/v1/delete_comment/', views.UserDetailsAPIView.as_view(), name='delete-comment-api'),
    
]

Desktop/myfirstprojectonjango/Resto-master/menu/urls.py
from django.urls import path
from . import views as menu_views

app_name = 'menu'


urlpatterns = [
    path('piece-de-resistance/', menu_views.PrimaryMealListView.as_view(), name='primary-meals'),
    path('primary_meal/<int:pk>/', menu_views.PrimaryMealDetailView.as_view(), name='primary-meal-details'),
    path('get_primary_meals/', menu_views.PrimaryMealsListAPIView.as_view(), name='primary-meals-api'),

    path('wines/', menu_views.WineListView.as_view(), name='wines'),
    path('wine/<int:pk>/', menu_views.WineDetailView.as_view(), name='wine-details'),
    path('get_all_wines/', menu_views.WineListAPIView.as_view(), name='wines-api'),
]

Desktop/myfirstprojectonjango/Resto-master/resto/urls.py
from django.contrib import admin
from django.conf import settings
from main import views as main_views
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    path('register/', main_views.registration, name='registration-page'),
    path('reservation/', include('reservation.urls'), name='reservation'),

    path('', include('main.urls')),
    path('teams/', include('teams.urls')),
    path('menu/', include('menu.urls')),

    # path('change_profile/', main_views.change_profile, name='change_profile'),
    path('feedbacks/', main_views.FeedbackListView.as_view(), name='all_feedbacks'),
    path('feedback/<int:pk>/', main_views.FeedbackDetailView.as_view(), name='feedback-details'),
    path('feedback/create/', main_views.FeedbackCreateView.as_view(), name='feedback-create'),
    path('feedback/update/<int:pk>/', main_views.FeedbackUpdateView.as_view(), name='feedback-update'),
    path('feedback/delete/<int:pk>/', main_views.FeedbackDeleteView.as_view(), name='feedback-delete'),
    path('api-auth/', include('rest_framework.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/myfirstprojectonjango/Resto-master/menu/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator


class PrimaryMeal(models.Model):
    name = models.CharField(
        verbose_name='Главное Блюдо',
        max_length=35
    )

    kitchen = models.CharField(
        verbose_name='Кухня',
        max_length=30
    )

    meal_image = models.ImageField(
        verbose_name='Фото',
        upload_to='meals'
    )

    ingredients = models.CharField(
        verbose_name='Ингредиенты',
        max_length=255
    )

    rate = models.ManyToManyField('Rate', related_name='primary_meals')

    price = models.IntegerField(
        verbose_name='Цена',
        validators=[MinValueValidator(100)]
    )

    date_created = models.DateTimeField(
        verbose_name='Дата добавления',
        default=timezone.now
    )

    def get_absolute_url(self):
        return reverse('menu:primary-meal-details', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name



class Wine(models.Model):
    CATEGORIES = (
        ('Sweet', 'Сладкое'),
        ('Half-Sweet', 'Полу-Сладкое'),
        ('Dry', 'Cухое'),
        ('Half-Dry', 'Полу-Сухое'),
    )

    COLORS = (
        ('White', 'Белое'),
        ('Red', 'Красное'),
        ('Pink', 'Розовое')
    )

    name = models.CharField(
        verbose_name='Название',
        max_length=35
    )

    wine_image = models.ImageField(
        verbose_name='Фото',
        upload_to='wines'
    )

    description = models.CharField(
        verbose_name='Описание',
        max_length=255
    )
    category = models.CharField(
        verbose_name='Категория',
        max_length=25,
        choices=CATEGORIES,
        default=CATEGORIES[0][1]
    )

    priority = models.IntegerField(
        validators=[MaxValueValidator(3)],
        verbose_name='Приоритет',
        default=None,
        blank=True
    )

    color = models.CharField(
        verbose_name='Цвет',
        max_length=10,
        choices=COLORS,
        default=COLORS[0][1]
    )

    rate = models.ManyToManyField('Rate', related_name='wines')

    price = models.IntegerField(
        verbose_name='Цена',
        validators=[MinValueValidator(100)]
    )

    date_created = models.DateTimeField(
        verbose_name='Дата добавления',
        default=timezone.now
    )

    def get_absolute_url(self):
        return reverse('menu:primary-meal-details', kwargs={'pk':self.pk})

    def __str__(self):
        return self.name



class Rate(models.Model):
    stars = models.IntegerField(
        verbose_name='Оценка',
        validators=[MaxValueValidator(5)],
        default=0,
        unique=True
    )

    date_created = models.DateTimeField(
        verbose_name='Дата создания',
        default=timezone.now
    )

    def __str__(self) -> str:
        return f'Оценка {self.stars}'



class Breakfast(models.Model):
    name = models.CharField(
        verbose_name='Название',
        max_length=35
    )


    photo = models.ImageField(
        verbose_name='Фотография',
        upload_to='breakfasts'
    )


    price = models.CharField(
        verbose_name='Цена',
        max_length=35
    )


    ingredients = models.CharField(
        verbose_name='Ингредиенты',
        max_length=35
    )

    date_to_present = models.DateTimeField(
        verbose_name='Актуально до'
    )

    date_created = models.DateTimeField(
        verbose_name='Дата создания',
        default=timezone.now
    )


    def __str__(self):
        return self.name

class Lanch(models.Model):
    name = models.CharField(
        verbose_name='Название',
        max_length=35
    )


    photo = models.ImageField(
        verbose_name='Фотография',
        upload_to='lanches'
    )


    price = models.CharField(
        verbose_name='Цена',
        max_length=35
    )


    ingredients = models.CharField(
        verbose_name='Ингредиенты',
        max_length=35
    )

    date_to_present = models.DateTimeField(
        verbose_name='Актуально до'
    )

    date_created = models.DateTimeField(
        verbose_name='Дата создания',
        default=timezone.now
    )

    def __str__(self):
        return self.name


class Dinner(models.Model):
    name = models.CharField(
        verbose_name='Название',
        max_length=35
    )


    photo = models.ImageField(
        verbose_name='Фотография',
        upload_to='dinners'
    )


    price = models.CharField(
        verbose_name='Цена',
        max_length=35
    )


    ingredients = models.CharField(
        verbose_name='Ингредиенты',
        max_length=35
    )

    date_to_present = models.DateTimeField(
        verbose_name='Актуально до'
    )

    date_created = models.DateTimeField(
        verbose_name='Дата создания',
        default=timezone.now
    )

    def __str__(self):
        return self.name

Desktop/myfirstprojectonjango/Resto-master/menu/views.py
import datetime as dt
from rest_framework import generics
from rest_framework.views import APIView
from django.views.generic import ListView, DetailView
from .models import Breakfast, PrimaryMeal, Wine, Lanch, Dinner


class PrimaryMealListView(ListView):
    model = PrimaryMeal
    template_name = 'menu/primary_meals.html'
    context_object_name = 'objects'

    def get_context_data(self, **kwargs):
        start = dt.datetime.strftime(dt.datetime.today() - dt.timedelta(days=1), '%Y-%m-%d')
        end = dt.datetime.strftime(dt.datetime.today() + dt.timedelta(days=365), '%Y-%m-%d')
        kwargs["breakfasts"] = Breakfast.objects.filter(date_to_present__range=[start, end])
        kwargs["lanches"] = Lanch.objects.filter(date_to_present__range=[start, end])
        kwargs["dinners"] = Dinner.objects.filter(date_to_present__range=[start, end])
        return super().get_context_data(**kwargs)


class PrimaryMealDetailView(DetailView):
    model = PrimaryMeal
    template_name = 'menu/primary_details.html'


class PrimaryMealsListAPIView(APIView):
    def get(self, request):
        pass



class WineListView(ListView):
    model = Wine
    template_name = 'menu/wines.html'

    def get_context_data(self, **kwargs):
        kwargs["wines_first_priority"] = Wine.objects.filter(priority__range=[1, 2])
        kwargs["wines_other_priority"] = Wine.objects.filter(priority__range=[3, 10])
        return super().get_context_data(**kwargs)


class WineDetailView(DetailView):
    model = Wine
    template_name = 'menu/wine_details.html'
    context_object_name = 'object'


class WineListAPIView(generics.ListAPIView):
    def get(self, request):
        pass

Desktop/myfirstprojectonjango/Resto-master/menu/templates/menu/primary_details.html
{% extends 'main/wrapper.html' %}

{% block content %}
<section id="gtco-special-dishes" class="bg-grey section-padding">
    <div class="container">
        <div class="section-content text-center">
            <div class="heading-section">
                <h2>
                    <span class="subheading">
                        {{object.name}}
                    </span>
                </h2>
            </div>

            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4"></div>
                <div class="col-lg-6 col-md-6 col-sm-12">

                    <div class="img-thumbnail rounded">
                        <img src="{{ object.meal_image.url }}" alt="{{ object.meal_image }}" style="max-width: 100%; height: auto;">
                    </div>


                    <div class="my-3">
                        {{object.kitchen}}
                    </div>

                    <div class="mt-2">
                        <h6>{{object.ingredients}}</h6>
                    </div>

                    <div class="mt-2">
                        <span class="subheading">
                            {{object.price}} сом
                        </span>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4"></div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

Desktop/myfirstprojectonjango/Resto-master/menu/templates/menu/primary_meals.html
{% extends 'main/wrapper.html' %}
{% load static %}

{% block content %}
<section id="gtco-special-dishes" class="bg-grey section-padding">
    <div class="container">
        <div class="section-content">
            <div class="heading-section text-center">
                <h2>
                    <span class="subheading">
                        Фирменные блюда
                    </span>
                </h2>
            </div>

            {% for object in objects %}
            <div class="row mt-5">
                <div class="col-lg-4 offset-lg-2 col-md-6 align-self-center mt-4 mt-md-0">
                    <a href="{% url 'menu:primary-meal-details' object.pk %}">
                        <img src="{{ object.meal_image.url }}" alt="{{ object.name }}" class="img-fluid shadow w-100">
                    </a>
                </div>
                <div class="col-lg-4 col-md-6 align-self-center py-5 ml-5">
                    <h2 class="special-number">0{{object.pk}}.</h2>
                    <div class="dishes-text">
                        <h3><span>{{ object.name }}</span><br>{{ object.kitchen }}</h3>
                        <p class="pt-3">{{ object.ingredients }}</p>
                        <h3 class="special-dishes-price">{{ object.price }} сом</h3>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<section id="gtco-menu" class="section-padding">
    <div class="container">
        <div class="section-content">
            <div class="row mb-5">
                <div class="col-md-12">
                    <div class="heading-section text-center">
                        <h2>
                            <span class="subheading">
                                Основное меню
                            </span>
                        </h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="menu-wrap">
                    <div class="heading-menu">
                        <h3 class="text-center mb-5">Завтраки</h3>
                    </div>
                    {% for meal in breakfasts %}
                    <div class="menus d-flex align-items-center">
                        <div class="menu-img rounded-circle">
                            <img class="img-fluid" src="{{ meal.photo.url }}" alt="{{ meal.name }}">
                        </div>
                        <div class="text-wrap">
                            <div class="row align-items-start">
                                <div class="col-8">
                                    <h4>{{ meal.name }}</h4>
                                </div>
                                <div class="col-4">
                                    <h4 class="text-muted menu-price">{{ meal.price }} сом</h4>
                                </div>
                            </div>
                            <p>{{ meal.ingredients }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="row">
                <div class="menu-wrap">
                    <div class="heading-menu">
                        <h3 class="text-center mb-5">Обеды</h3>
                    </div>
                    {% for meal in lanches %}
                    <div class="menus d-flex align-items-center">
                        <div class="menu-img rounded-circle">
                            <img class="img-fluid" src="{{ meal.photo.url }}" alt="{{ meal.name }}">
                        </div>
                        <div class="text-wrap">
                            <div class="row align-items-start">
                                <div class="col-8">
                                    <h4>{{ meal.name }}</h4>
                                </div>
                                <div class="col-4">
                                    <h4 class="text-muted menu-price">{{ meal.price }} сом</h4>
                                </div>
                            </div>
                            <p>{{ meal.ingredients }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>

            <div class="row">
                <div class="menu-wrap">
                    <div class="heading-menu">
                        <h3 class="text-center mb-5">Ужины</h3>
                    </div>
                    {% for meal in dinners %}
                    <div class="menus d-flex align-items-center">
                        <div class="menu-img rounded-circle">
                            <img class="img-fluid" src="{{ meal.photo.url }}" alt="{{ meal.name }}">
                        </div>
                        <div class="text-wrap">
                            <div class="row align-items-start">
                                <div class="col-8">
                                    <h4>{{ meal.name }}</h4>
                                </div>
                                <div class="col-4">
                                    <h4 class="text-muted menu-price">{{ meal.price }} сом</h4>
                                </div>
                            </div>
                            <p>{{ meal.ingredients }}</p>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}

Desktop/myfirstprojectonjango/Resto-master/menu/templates/menu/wine_details.html
{% extends 'main/wrapper.html' %}

{% block content %}
<section id="gtco-special-dishes" class="bg-grey section-padding">
    <div class="container">
        <div class="section-content text-center">
            <div class="heading-section">
                <h2>
                    <span class="subheading">
                        {{object.name}}
                    </span>
                </h2>
            </div>

            <div class="row">
                <div class="col-lg-3 col-md-3 col-sm-4"></div>
                <div class="col-lg-6 col-md-6 col-sm-12">
                    <div class="img-thumbnail rounded">
                        <img src="{{ object.wine_image.url }}" alt="{{ object.wine_image }}" style="max-width: 100%; height: auto;">
                    </div>

                    <div class="my-3">
                        <h5>{{object.description}}</h5>
                    </div>

                    <div class="mt-2">
                        <p>{{object.color}} - {{object.category}}</p>
                    </div>

                    <div class="mt-2">
                        <span class="subheading">
                            <b>{{object.price}} сом</b>
                        </span>
                    </div>
                </div>
                <div class="col-lg-3 col-md-3 col-sm-4"></div>
            </div>
        </div>
    </div>
</section>

{% endblock content %}

Desktop/myfirstprojectonjango/Resto-master/menu/templates/menu/wines.html
{% extends 'main/wrapper.html' %}
{% load static %}

{% block content %}
<section id="gtco-special-dishes" class="bg-grey section-padding">
    <div class="container">
        <div class="section-content">
            <div class="heading-section text-center">
                <h2>
                    <span class="subheading">
                        Лучшие Вина
                    </span>
                </h2>
            </div>
            {% for object in wines_first_priority %}
            <div class="row mt-5">

                <div class="col-lg-4 offset-lg-2 col-md-6 align-self-center mt-4 mt-md-0">
                    <a href="{% url 'menu:wine-details' object.pk %}">
                        <img src="{{ object.wine_image.url }}" alt="" class="img-fluid shadow w-100">
                    </a>
                </div>

                <div class="col-lg-4 col-md-6 align-self-center py-5 ml-5">
                    <h2 class="special-number">0{{object.pk}}.</h2>
                    <div class="dishes-text">
                        <h3><span>{{ object.name }}</span><br>{{ object.category }} {{ object.color }}</h3>
                        <p class="pt-3">{{ object.description }}</p>
                        <h3 class="special-dishes-price">{{ object.price }} сом</h3>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>

<section id="gtco-menu" class="section-padding">
    <div class="container">
        <div class="section-content">
            <div class="row mb-5">
                <div class="col-md-12">
                    <div class="heading-section text-center">
                        <h2>
                            <span class="subheading">
                                Каталог
                            </span>
                        </h2>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="menu-wrap">
                    <div class="heading-menu">
                        <h3 class="text-center mb-5">Основные Вина</h3>
                    </div>
                    {% for wine in wines_other_priority %}
                    <div class="menus d-flex align-items-center">
                        <div class="menu-img rounded-circle">
                            <img class="img-fluid" src="{{ wine.wine_image.url }}" alt="{{ meal.name }}">
                        </div>
                        <div class="text-wrap">
                            <div class="row align-items-start">
                                <div class="col-8">
                                    <h4>{{ wine.name }}</h4>
                                </div>
                                <div class="col-4">
                                    <h4 class="text-muted menu-price">{{ wine.price }} сом</h4>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock content %}