Desktop/myfirstprojectonjango/Resto-master/main/urls.py
from django.urls import path
from . import views


app_name = 'main'

urlpatterns = [
    path('', views.MainView.as_view(), name='main'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('api/v1/get_all_users/', views.UserListAPIView.as_view(), name='get-all-users-api'),
    path('api/v1/update_user/', views.UserUpdateAPIView.as_view(), name='create-users-api'),

    path('api/v1/get_all_feedbacks/', views.FeedbackListAPIView.as_view(), name='get-all-feedbacks-api'),
    path('api/v1/create_feedback/', views.FeedbackCreateAPIView.as_view(), name='create-feedback-api'),
    path('api/v1/update_feedback/', views.FeedbackUpdateAPIView.as_view(), name='update-feedback-api'),
    path('api/v1/delete_feedback/', views.FeedbackDeleteView.as_view(), name='delete-feedback-api'),

    path('api/v1/get_all_comments/', views.CommentListAPIView.as_view(), name='get-all-comments-api'),
    path('api/v1/create_comment/', views.CommentListAPIView.as_view(), name='update-comment-api'),
    path('api/v1/update_comment/', views.UserDetailsAPIView.as_view(), name='update-comment-api'),
    path('api/v1/delete_comment/', views.UserDetailsAPIView.as_view(), name='delete-comment-api'),
    
]

Desktop/myfirstprojectonjango/Resto-master/menu/urls.py
from django.urls import path
from . import views as menu_views

app_name = 'menu'


urlpatterns = [
    path('piece-de-resistance/', menu_views.PrimaryMealListView.as_view(), name='primary-meals'),
    path('primary_meal/<int:pk>/', menu_views.PrimaryMealDetailView.as_view(), name='primary-meal-details'),
    path('get_primary_meals/', menu_views.PrimaryMealsListAPIView.as_view(), name='primary-meals-api'),

    path('wines/', menu_views.WineListView.as_view(), name='wines'),
    path('wine/<int:pk>/', menu_views.WineDetailView.as_view(), name='wine-details'),
    path('get_all_wines/', menu_views.WineListAPIView.as_view(), name='wines-api'),
]

Desktop/myfirstprojectonjango/Resto-master/reservation/urls.py
from django.urls import path
from . import views


app_name = 'reservation'


urlpatterns = [
    path('', views.reserve, name='reserve'),
    path('reservations/', views.display_reservations, name='my-reservations'),
    path('get-all-reservations/', views.ReservationListAPIView.as_view(), name='get-all-orders'),
    path('create-reservation/', views.ReservationCreateAPIView.as_view(), name='create-reservation'),
]

Desktop/myfirstprojectonjango/Resto-master/resto/urls.py
from django.contrib import admin
from django.conf import settings
from main import views as main_views
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(template_name='main/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='main/logout.html'), name='logout'),
    path('register/', main_views.registration, name='registration-page'),
    path('reservation/', include('reservation.urls'), name='reservation'),

    path('', include('main.urls')),
    path('teams/', include('teams.urls')),
    path('menu/', include('menu.urls')),

    # path('change_profile/', main_views.change_profile, name='change_profile'),
    path('feedbacks/', main_views.FeedbackListView.as_view(), name='all_feedbacks'),
    path('feedback/<int:pk>/', main_views.FeedbackDetailView.as_view(), name='feedback-details'),
    path('feedback/create/', main_views.FeedbackCreateView.as_view(), name='feedback-create'),
    path('feedback/update/<int:pk>/', main_views.FeedbackUpdateView.as_view(), name='feedback-update'),
    path('feedback/delete/<int:pk>/', main_views.FeedbackDeleteView.as_view(), name='feedback-delete'),
    path('api-auth/', include('rest_framework.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Desktop/myfirstprojectonjango/Resto-master/teams/urls.py
from django.contrib.auth import default_app_config
from django.urls import path
from . import views

app_name = 'teams'

urlpatterns = [
    path('', views.TeamMemberCreateView.as_view(), name='all-team'),
    path('details/<int:pk>/', views.TeamMemberDetailView.as_view(), name='member-details')
]

Desktop/myfirstprojectonjango/Resto-master/main/models.py
from django.db import models
from django.utils import timezone
from django.shortcuts import reverse
from django.contrib.auth.models import User

class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='profile'
    )

    user_profile_photo = models.ImageField(
        upload_to='user_profiles',
        verbose_name='Фото профиля',
        default='anonym_author.png'
    )

    def __str__(self):
        return f'Профиль пользователя {self.user.first_name} {self.user.last_name}'


class Feedback(models.Model):
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор Отзыва'
    )

    feedback_text = models.TextField(
        verbose_name='Оставьте Отзыв'
    )

    date_created = models.DateTimeField(
        verbose_name='Дата создания отзыва',
        default=timezone.now
    )

    def get_absolute_url(self):
        return reverse('feedback-details', kwargs={'pk':self.pk})

    def __str__(self):
        return f'{self.feedback_text}'


class Comment(models.Model):
    '''Данная модель создаёт объект комментария в привязанного к отзыву.'''
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор комментария'
    )

    assigned_to_feedback = models.ForeignKey(
        Feedback,
        on_delete=models.CASCADE,
        verbose_name='Отзыв',
        related_name='comments'
    )

    comment_text = models.TextField(
        verbose_name='Текст Комментария'
    )

    date_created = models.DateTimeField(
        verbose_name='Дата создания комментария',
        default=timezone.now)

    def __str__(self):
        return f'Комментарий {self.assigned_to_feedback}'

Desktop/myfirstprojectonjango/Resto-master/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms.models import model_to_dict


class RegistrationForm(UserCreationForm):
    first_name = forms.CharField(
        min_length=4,
        max_length=50,
        label='Имя'
    )

    last_name = forms.CharField(
        min_length=4,
        max_length=50,
        label='Фамилия'
    )

    email = forms.EmailField(
        max_length=50,
        min_length=10,
        widget=forms.EmailInput,
        label='Почта'
    )

Desktop/myfirstprojectonjango/Resto-master/main/views.py
from django.db.models import fields
from rest_framework.response import Response
from rest_framework.serializers import Serializer
from .forms import RegistrationForm
from .models import Feedback, Comment
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import ListView, DetailView, CreateView, DeleteView, UpdateView, View


from rest_framework.views import APIView
from rest_framework import generics, status
from rest_framework.permissions import IsAdminUser, IsAuthenticated, IsAuthenticatedOrReadOnly, AllowAny
from .serializers import CommentSerializer, UserSerializer, FeedbackSerializer
from django.contrib.auth.models import User

from main import serializers
from django.contrib.auth import authenticate

class MainView(View):
    def get(self, request):
        return render(
            request=request,
            template_name='main/index.html'
        )


class AboutView(View):
   def get(self, request, *args, **kwargs):
        return render(
            request=request,
            template_name='main/about.html'
        )


def registration(request):
    if request.method == 'POST':
        registration_form = RegistrationForm(request.POST)

        if registration_form.is_valid():
            form = registration_form.save(commit=False)
            form.first_name = registration_form.cleaned_data["first_name"]
            form.last_name = registration_form.cleaned_data["last_name"]
            form.email = registration_form.cleaned_data["email"]
            form.save()
            return redirect('main:main')

    else:
        registration_form = RegistrationForm()

    return render(
        request=request,
        template_name='main/registration.html',
        context={"sign_in_form": registration_form}
    )


class FeedbackListView(ListView):
    model = Feedback
    template_name = 'main/feedback_list.html'

    def get_queryset(self, *args, **kwargs):
        overried_queryset = super(FeedbackListView, self).get_queryset(*args, **kwargs)
        result = overried_queryset.order_by('-date_created')
        return result


class FeedbackDetailView(DetailView):
    model = Feedback
    template_name='main/feedback_details.html'

    def get_context_data(self, **kwargs):
        feedback = self.get_object()
        kwargs['comment_list'] = Comment.objects.filter(assigned_to_feedback=feedback.pk)
        return super().get_context_data(**kwargs)


class FeedbackCreateView(LoginRequiredMixin, CreateView):
    model = Feedback
    fields = ['feedback_text',]
    template_name = 'main/feedback_create.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)



class FeedbackUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Feedback
    fields = ['feedback_text',]
    template_name = 'main/feedback_update.html'

    def test_func(self):
        feedback = self.get_object()
        if self.request.user == feedback.author:
            return True
        return False


class FeedbackDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Feedback
    success_url = "/feedbacks/"
    template_name = 'main/feedback_delete.html'

    def test_func(self):
        feedback = self.get_object()
        if self.request.user == feedback.author:
            return True
        return False





####################################################################################################
####################################### Django REST API ############################################
####################################################################################################

class UserListAPIView(generics.ListAPIView):
    permission_classes = [AllowAny,]
    serializer_class = UserSerializer

    queryset = User.objects.all()


class UserDetailsAPIView(APIView):
    permission_classes = [AllowAny,]
    serializer_class = UserSerializer

    def get(self, request):
        user = User.objects.filter(username=request.user).first()
        if user:
            return Response(
                data={
                    "success": True,
                    "result": user
                },
                status=status.HTTP_200_OK
            )
        return Response(
                data={
                    "success": False,
                    "result": "Ты кто такой?"
                },
                status=status.HTTP_401_UNAUTHORIZED
            )



class UserUpdateAPIView(generics.UpdateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = UserSerializer

    def put(self, request):
        user = User.objects.get(id=request.data.get('id'))
        serializer = self.serializer_class(user, data=request.data, partial=True)
        serializer.is_valid(raise_exception=True)
        serializer.save()

        return Response(
            data={
                "success": True,
                "result": "User has been UPDATED successfully!"
            }
        )


class UserDeleteAPIView(generics.DestroyAPIView):
    permission_classes = (AllowAny,)
    serializer_class = UserSerializer

    def delete(self, request):
        user = User.objects.get(id=request.data.get('id'))
        user.delete()
        return Response(
            data={
                "success": True,
                "result": "User has been DELETED successfully!"
            }
        )


class FeedbackListAPIView(generics.ListAPIView):
    permission_classes = [AllowAny,]
    serializer_class = FeedbackSerializer
    queryset = Feedback.objects.all()



class FeedbackCreateAPIView(generics.CreateAPIView):
    permission_classes = [AllowAny,]
    serializer_class = FeedbackSerializer

    def post(self, request):
        try:
            if request.data.get('author_id'):
                user = User.objects.get(pk=request.data.get('author_id'))
                author_id = user.pk
            else:
                author_id = None

        except User.DoesNotExist:
            return Response(
            data={
                "success":False,
                "result":"Такого пользователя нет в Базе Данных или Вы не указали author_id."
            },
            status=status.HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS
        )


        serializer = FeedbackSerializer(
            data=request.data, 
            context={
                "author_id": author_id,
                "request": request
            }
        )
        serializer.is_valid(raise_exception=True)
        serializer.save()
        return Response(
            data={
                "success":True,
                "result":"Отзыв был оставлен успешно"
            },
            status=status.HTTP_201_CREATED
        )



class FeedbackUpdateAPIView(generics.UpdateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = FeedbackSerializer

    def put(self, request):
        try:
            feedback_id = Feedback.objects.get(pk=request.data.get('feedback_id'))

            serializer = FeedbackSerializer(
                instance=feedback_id,
                data=request.data,
                partial=True
            )

            serializer.is_valid(raise_exception=True)
            serializer.save()
            return Response(
                data={
                    "success":True,
                    "result":"Отзыв был ОБНОВЛЁН успешно"
                },
                status=status.HTTP_200_OK
            )
        except Feedback.DoesNotExist:
            return Response(
            data={
                "success":False,
                "result":"Отзыв не найден!"
            },
            status=status.HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS
        )


class FeedbackDeleteAPIView(generics.DestroyAPIView):
    permission_classes = (AllowAny,)
    serializer_class = FeedbackSerializer

    def delete(self, request):
        try:
            feedback_id = Feedback.objects.get(pk=request.data.get('feedback_id'))
            feedback_id.delete()
            return Response(
                data={
                    "success":True,
                    "result":"Отзыв был УДАЛЁН успешно"
                },
                status=status.HTTP_202_ACCEPTED
            )
        except Feedback.DoesNotExist:
            return Response(
            data={
                "success":False,
                "result":"Отзыв не найден!"
            },
            status=status.HTTP_451_UNAVAILABLE_FOR_LEGAL_REASONS
        )



class CommentListAPIView(generics.ListAPIView):
    permission_classes = (AllowAny,)
    serializer_class = CommentSerializer

    def get(self, request):
        serializer = self.serializer_class(Comment.objects.all(), many=True)
        return Response(
            data={
                "success": True,
                "result": serializer.data
            }
        )

class CommentCreateAPIView(generics.CreateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = CommentSerializer

    def get(self, request):
        serializer = self.serializer_class(Comment.objects.all(), many=True)
        return Response(
            data={
                "success": True,
                "result": serializer.data
            }
        )

class CommentListAPIView(generics.UpdateAPIView):
    permission_classes = (AllowAny,)
    serializer_class = CommentSerializer

    def get(self, request):
        serializer = self.serializer_class(Comment.objects.all(), many=True)
        return Response(
            data={
                "success": True,
                "result": serializer.data
            }
        )

class CommentListAPIView(generics.DestroyAPIView):
    permission_classes = (AllowAny,)
    serializer_class = CommentSerializer

    def delete(self, request):
    
        return Response(
            data={
                "success": True,

Desktop/myfirstprojectonjango/Resto-master/main/templates/main/change_profile.html
{% extends 'main/wrapper.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
    <div class="row">
        <div class="col-12">
            <div class="section-content">


            </div>
        </div>
    </div>
</div>
{% endblock content %}

Desktop/myfirstprojectonjango/Resto-master/main/templates/main/feedback_create.html
{% extends 'main/wrapper.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center text-center">
        <div class="col-4">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group text-center">
                    <h3 style="font-weight: bold;">{{ form.feedback_text.label}}</h3>
                    {{ form.feedback_text}}
                </div>
                <button type="submit" class="btn btn-primary">Добавить Отзыв</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

Desktop/myfirstprojectonjango/Resto-master/main/templates/main/feedback_update.html
{% extends 'main/wrapper.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container py-5">
    <div class="row justify-content-center text-center">
        <div class="col-4">
            <form method="POST">
                {% csrf_token %}
                <div class="form-group text-center">
                    <h3 style="font-weight: bold;">{{ form.feedback_text.label}}</h3>
                    {{ form.feedback_text}}
                </div>
                <button type="submit" class="btn btn-primary">Изменить Отзыв</button>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

Desktop/myfirstprojectonjango/Resto-master/main/templates/main/wrapper.html
{% load static %}
{% load crispy_forms_tags %}
<!DOCTYPE html>

<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{{ title }}</title>
    <meta name="description" content="Resto">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- External CSS -->
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/select2/select2.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owlcarousel/owl.carousel.min.css' %}">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">


    <link rel="stylesheet" href="https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.css">
    <!-- Fonts -->
    <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700|Josefin+Sans:300,400,700">
    <link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/style.min.css' %}">

    <!-- Modernizr JS for IE8 support of HTML5 elements and media queries -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
        crossorigin="anonymous"></script>
</head>

<body data-spy="scroll" data-target="#navbar" class="static-layout">
    <div id="side-nav" class="sidenav">
        <a href="javascript:void(0)" id="side-nav-close">&times;</a>

        <div class="sidenav-content">
            <p>
                ITC Company Razakov 32
            </p>
            <p>
                <span class="fs-16 primary-color">(+996) 550 271098</span>
            </p>
            <p>geekgant@gmail.com</p>
        </div>
    </div>

    <div id="side-search" class="sidenav">
        <a href="javascript:void(0)" id="side-search-close">&times;</a>
        <div class="sidenav-content">
            <form action="">

                <div class="input-group md-form form-sm form-2 pl-0">
                    <input class="form-control my-0 py-1 red-border" type="text" placeholder="Search"
                        aria-label="Search">
                    <div class="input-group-append">
                        <button class="input-group-text red lighten-3" id="basic-text1">
                            <i class="fas fa-search text-grey" aria-hidden="true"></i>
                        </button>
                    </div>
                </div>

            </form>
        </div>
    </div>

    <div id="canvas-overlay"></div>
    <div class="boxed-page">
        <nav id="navbar-header" class="navbar navbar-expand-lg">
            <div class="container">
                <a class="navbar-brand navbar-brand-center d-flex align-items-center p-0 only-mobile"
                    href="{% url 'main:index' %">
                    <img src="{% static 'img/logo.png' %}" alt="Main Logo">
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <span class="lnr lnr-menu"></span>
                </button>

                <div class="collapse navbar-collapse justify-content-between" id="navbarSupportedContent">
                    <ul class="navbar-nav d-flex justify-content-between">
                        <li class="nav-item only-desktop">
                            <a class="nav-link" id="side-nav-open" href="#">
                                <span class="lnr lnr-menu"></span>
                            </a>
                        </li>
                        <div class="d-flex flex-lg-row flex-column">
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'main:main' %}">Главная<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'main:about' %}">О нас</a>
                            </li>

                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Меню
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'menu:primary-meals' %}">Основные Блюда</a>
                                    <a class="dropdown-item" href="{% url 'menu:wines' %}">Вина</a>
                                </div>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'all_feedbacks' %}">Отзывы</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'teams:all-team' %}">Повара</a>
                            </li>
                            </li>
                        </div>
                    </ul>

                    <a class="navbar-brand navbar-brand-center d-flex align-items-center only-desktop"
                        href="{% url 'main:main' %}">
                        <img src="{% static 'img/logo.png' %}" alt="Main Logo">
                    </a>
                    <ul class="navbar-nav d-flex justify-content-between">
                        <div class="d-flex flex-lg-row flex-column">

                            {% if user.is_authenticated %}
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'reservation:my-reservations' %}">История<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link" href="{% url 'reservation:reserve' %}">Забронировать</a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'logout' %}">Выйти<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            {% else %}
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'login' %}">Войти<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            <li class="nav-item active">
                                <a class="nav-link" href="{% url 'registration-page' %}">Зарегистрироваться<span
                                        class="sr-only">(current)</span></a>
                            </li>
                            {% endif %}
                        </div>
                        <li class="nav-item">
                            <a id="side-search-open" class="nav-link" href="#">
                                <span class="lnr lnr-magnifier"></span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        {% block content %}{% endblock %}
        <footer class="mastfoot pb-5 bg-white pt-5 pb-0 mt-5" style="border-top:3px solid #b3b3cc;">
            <div class="inner container">
                <div class="row">
                    <div class="col-lg-4">
                        <div class="footer-widget pr-lg-5 pr-0">
                            <img src="{% static 'img/logo.png' %}" class="img-fluid footer-logo mb-3" alt="Main Logo">
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et obcaecati quisquam id sit
                                omnis explicabo voluptate aut placeat, soluta, nisi ea magni facere, itaque incidunt
                                modi? Magni, et voluptatum dolorem.</p>
                            <nav class="nav nav-mastfoot justify-content-start">
                                <a class="nav-link" href="#">
                                    <i class="fab fa-facebook-f"></i>
                                </a>
                                <a class="nav-link" href="#">
                                    <i class="fab fa-twitter"></i>
                                </a>
                                <a class="nav-link" href="#">
                                    <i class="fab fa-instagram"></i>
                                </a>
                            </nav>
                        </div>

                    </div>
                    <div class="col-lg-4">
                        <div class="footer-widget px-lg-5 px-0">
                            <h4>Open Hours</h4>
                            <ul class="list-unstyled open-hours">
                                <li class="d-flex justify-content-between"><span>Monday</span><span>9:00 - 24:00</span>
                                </li>
                                <li class="d-flex justify-content-between"><span>Tuesday</span><span>9:00 - 24:00</span>
                                </li>
                                <li class="d-flex justify-content-between"><span>Wednesday</span><span>9:00 -
                                        24:00</span></li>
                                <li class="d-flex justify-content-between"><span>Thursday</span><span>9:00 -
                                        24:00</span></li>
                                <li class="d-flex justify-content-between"><span>Friday</span><span>9:00 - 02:00</span>
                                </li>
                                <li class="d-flex justify-content-between"><span>Saturday</span><span>9:00 -
                                        02:00</span></li>
                                <li class="d-flex justify-content-between"><span>Sunday</span><span> Closed</span></li>
                            </ul>
                        </div>

                    </div>

                    <div class="col-lg-4">
                        <div class="footer-widget pl-lg-5 pl-0">
                            <h4>Newsletter</h4>
                            <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit.</p>
                            <form id="newsletter">
                                <div class="form-group">
                                    <input type="email" class="form-control" id="emailNewsletter"
                                        aria-describedby="emailNewsletter" placeholder="Enter email">
                                </div>
                                <button type="submit" class="btn btn-primary w-100">Submit</button>
                            </form>
                        </div>

                    </div>
                    <div class="col-md-12 d-flex align-items-center">
                        <p class="mx-auto text-center mb-0">Copyright 2019. All Right Reserved. Design by <a
                                href="https://gettemplates.co" target="_blank">GetTemplates</a></p>
                    </div>

                </div>
            </div>
        </footer>
    </div>
    <!-- External JS -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.22.2/moment.min.js"></script>
    <script src="{% static 'vendor/bootstrap/popper.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/select2/select2.min.js' %}"></script>
    <script src="{% static 'vendor/owlcarousel/owl.carousel.min.js' %}"></script>
    <script src="https://cdn.rawgit.com/noelboss/featherlight/1.7.13/release/featherlight.min.js"></script>
    <script src="{% static 'vendor/stellar/jquery.stellar.js' %}" type="text/javascript" charset="utf-8"></script>
    <script
        src="https://cdnjs.cloudflare.com/ajax/libs/tempusdominus-bootstrap-4/5.0.1/js/tempusdominus-bootstrap-4.min.js"></script>

    <!-- Main JS -->
    <script src="{% static 'js/app.min.js' %}"></script>
</body>

</html>